const fs = require('fs');
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
const html = fs.readFileSync('c:/Users/devil/Documents/video loop site project/index.html', 'utf8');
const dom = new JSDOM(html);
const document = dom.window.document;
console.log('Sidebar card:', document.querySelector('.sidebar-card') !== null);
console.log('Tab content container:', document.querySelector('.tab-content-container') !== null);
console.log('Tab up next:', document.querySelector('#tab-up-next') !== null);
console.log('Tab content container parent:', document.querySelector('.tab-content-container').parentNode.className);
console.log('Tab favorites hidden?', document.getElementById('tab-favorites').classList.contains('hidden'));
console.log('Tab favorites active?', document.getElementById('tab-favorites').classList.contains('active'));
console.log('Fav auth required hidden?', document.getElementById('fav-auth-required').classList.contains('hidden'));
